### ISSUE TITLE
questions in paper

### ISSUE THREAD

**Issue by chouqin3** [xudonmao/LSGAN#3]
You mentioned in paper, when it follows b-a=2,  that satifies Pearson divergence. But the formula doesn't follow the condition. Please let me know the tricks.
![微信截图_20190425110706](https://user-images.githubusercontent.com/12481496/56707315-e775ab00-674a-11e9-826b-f264d4c6e654.png)

**Comment by XiaoqiangZhou** [comment]
@chouqin3 There are two kinds of settings: 1) `for D: real_data=1, fake_data=0, for G: target=1` and 2) `for D: real_data=1, fake_data=0, for G: target=0.5`. The second setting follows` b-a=2` in some way and statisies the Pearson divergence. But as author claimed: 
> observe that Equation 8 and Equation 9 show similar performance.

So he uses the first setting, which is same with setting in GAN (Ian Goodfellow, NIPS2014)

**Comment by chouqin3** [comment]
thank you for answer
